#!/usr/bin/env bash

#herbstluftwm start
hc() {
    herbstclient "$@"
}

hc emit_hook reload

~/.config/herbstluftwm/autostart.d/keybinds
~/.config/herbstluftwm/autostart.d/attributes
~/.config/herbstluftwm/autostart.d/rules
~/.config/herbstluftwm/autostart.d/monitor-settings

# unlock, just to be sure
hc unlock

# only load autostarts on first startup
if hc silent new_attr bool my_not_first_autostart ; then
    ~/.config/herbstluftwm/autostart.d/autostart
fi
