#!/usr/bin/env bash

function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}

#herbstluftwm start
hc() {
    herbstclient "$@"
}

hc emit_hook reload

~/.config/herbstluftwm/autostart.d/keybinds
~/.config/herbstluftwm/autostart.d/attributes
~/.config/herbstluftwm/autostart.d/rules
~/.config/herbstluftwm/autostart.d/monitor-settings

# unlock, just to be sure
hc unlock

~/.config/herbstluftwm/autostart.d/autostart
