#!/usr/bin/env bash

#herbstluftwm start
hc() {
    herbstclient "$@"
}

#launching polybar & tray icons
~/.config/polybar/launch.sh &
volumeicon &
nm-applet &

# general applications
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
xfce4-power-manager &

# compositor & wallpaper
~/.config/herbstluftwm/scripts/picom-launch.sh &
nitrogen --restore &

#keybinds are in ~/.config/sxhkd/sxhkdrc
sxhkd &

# misc applications
numlockx on &
setxkbmap -option caps:escape &
