wallpaper {
    monitor = eDP-1
    path = ~/.config/simonkir/backgrounds/
    order = random
    timeout = 43200
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/simonkir/backgrounds/
    order = random
    timeout = 43200
}

wallpaper {
    monitor =
    path = ~/.config/simonkir/backgrounds/
    order = random
    timeout = 43200
}

splash = false