$font = Carlito

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(82aaffee) rgba(c792eaee) 315deg
    check_color = rgba(ffcb6bee) rgba(c3e88dee) 315deg
    fail_color = rgba(ff5370ee) rgba(c792eaee) 315deg

    font_color = rgba(82aaffee)
    fade_on_empty = false
    rounding = 10

    font_family = $font
    # placeholder_txt = Input password...
    fail_text = $PAMFAIL$FPRINTFAIL

    dots_spacing = 0.3

    position = 150, 300
    halign = left
    valign = bottom
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = -50, -50
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = -50, -200
    halign = right
    valign = top
}
