$font = Carlito Bold

$black =      rgba(292d3eff)
$red =        rgba(ff5370ff)
$green =      rgba(c3e88dff)
$yellow =     rgba(ffcb6bff)
$blue =       rgba(82aaffff)
$magenta =    rgba(c792eaff)
$cyan =       rgba(89ddffff)
$white =      rgba(eeffffff)
$foreground = rgba(eeffffff)
$background = rgba(292d3eff)


general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot

    blur_passes = 3
    blue_size = 7
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3

    inner_color = rgba(0, 0, 0, 0.0) # no fill
    outer_color = $blue $magenta 315deg
    check_color = $yellow $green 315deg
    fail_color = $red $magenta 315deg

    font_color = $blue
    fade_on_empty = false
    rounding = 10

    font_family = $font
    font_style = bold
    placeholder_text = $USER
    fail_text = $PAMFAIL$FPRINTFAIL

    dots_spacing = 0.3
    dots_size = 0.24

    position = 0, -150
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:60000] date +"%H:%M" # update every 60 seconds
    color = $blue
    font_size = 90
    font_family = $font
    position = 0, 150
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d. %B %Y" # update every 60 seconds
    color = $blue
    font_size = 25
    font_family = $font

    position = 0, 50
    halign = center
    valign = center
}
