# * general settings
[scrolling]
history = 50000

[shell]
program = "/usr/bin/fish"

[window]
opacity = 0.9

[window.padding]
x = 11
y = 11

# * theme
[colors.bright]
black = "#242837"
blue = "#5fafff"
cyan = "#5fd7ff"
green = "#afff00"
magenta = "#d787d7"
red = "#ff0000"
white = "#e4e4e4"
yellow = "#ffd700"

[colors.normal]
black = "#292d3e"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#ff5370"
white = "#eeffff"
yellow = "#ffcb6b"

[colors.primary]
background = "#292d3e"
foreground = "#eeffff"

# * font
[font]
size = 10.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

